server:
  port: 30002

rocketmq:
  consumer:
    isOnOff: on
    groupName: rocketmq-shiyakun
    namesrvAddr: 192.168.13.130:9876;192.168.13.131:9876
    topics: Topic-2
    consumeThreadMin: 20
    consumeThreadMax: 64
    consumeMessageBatchMaxSize: 1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rocketmq?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: syk123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:

  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.shi.rocketmqconsumer.entity
  global-config:
    id-type: 0
#    field-strategy: 2
    db-column-underline: true
    #table-prefix: mp_
    refresh-mapper: true
    #capital-mode: true
#    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
#    logic-delete-value: 1
#    logic-not-delete-value: 0
#    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
#    meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    multipleResultSetsEnabled: false #
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: false
    return-instance-for-empty-row: false